name: turnopronto_app
description: App Android/iOS para profissionais da plataforma TurnoPronto.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
