import 'dart:convert';
import 'dart:io';
import '../models/job.dart';

class ApiException implements Exception { ApiException(this.message); final String message; @override String toString()=>message; }
class ApiService {
  ApiService({String? baseUrl}):baseUrl=baseUrl??const String.fromEnvironment('API_URL',defaultValue:'http://10.0.2.2/turnopronto_web/api/v1');
  final String baseUrl; String? token; bool demoMode=false;
  Future<Map<String,dynamic>> _request(String method,String path,{Map<String,dynamic>? body})async{final client=HttpClient();try{final request=await client.openUrl(method,Uri.parse('$baseUrl$path'));request.headers.contentType=ContentType.json;request.headers.set(HttpHeaders.acceptHeader,'application/json');if(token!=null)request.headers.set(HttpHeaders.authorizationHeader,'Bearer $token');if(body!=null)request.write(jsonEncode(body));final response=await request.close();final raw=await response.transform(utf8.decoder).join();final dynamic decoded=raw.isEmpty?<String,dynamic>{}:jsonDecode(raw);if(decoded is! Map)throw ApiException('Resposta inválida do servidor.');final data=Map<String,dynamic>.from(decoded);if(response.statusCode<200||response.statusCode>=300||data['ok']==false)throw ApiException((data['error']??'Erro ${response.statusCode}').toString());return data;}on SocketException{throw ApiException('Não foi possível conectar ao XAMPP em $baseUrl');}finally{client.close(force:true);}}
  Future<void> login(String email,String password)async{final data=await _request('POST','/auth/login',body:{'email':email,'password':password});token=data['token']?.toString();demoMode=false;}
  void loginDemo(){demoMode=true;token=null;}
  Future<List<Job>> opportunities()async{if(demoMode)return demoJobs();final data=await _request('GET','/opportunities');final list=data['data'];if(list is! List)return <Job>[];return list.map((e)=>Job.fromJson(Map<String,dynamic>.from(e as Map))).toList();}
  Future<Job> job(int id)async{if(demoMode)return demoJobs().firstWhere((e)=>e.id==id,orElse:()=>demoJobs().first);final data=await _request('GET','/shifts/$id');return Job.fromJson(Map<String,dynamic>.from(data['data'] as Map));}
  Future<int> accept(int id)async{if(demoMode)return 900+id;final data=await _request('POST','/shifts/$id/accept');return int.parse(data['assignment_id'].toString());}
  Future<List<Assignment>> assignments()async{if(demoMode)return demoAssignments();final data=await _request('GET','/assignments');final list=data['data'];if(list is! List)return <Assignment>[];return list.map((e)=>Assignment.fromJson(Map<String,dynamic>.from(e as Map))).toList();}
  Future<Assignment> assignment(int id)async{if(demoMode)return demoAssignments().first;final data=await _request('GET','/assignments/$id');return Assignment.fromJson(Map<String,dynamic>.from(data['data'] as Map));}
  Future<void> checkIn(int id,{String pin=''})async{if(demoMode)return;await _request('POST','/assignments/$id/check-in',body:{'pin':pin});}
  Future<void> checkOut(int id)async{if(demoMode)return;await _request('POST','/assignments/$id/check-out');}
  Future<Map<String,dynamic>> earnings()async{if(demoMode)return <String,dynamic>{'summary':<String,dynamic>{'total':6420.0,'available':780.0}};final data=await _request('GET','/earnings');return Map<String,dynamic>.from(data['data'] as Map);}
  static List<Job> demoJobs(){final now=DateTime.now();DateTime d(int add,int h,[int m=0])=>DateTime(now.year,now.month,now.day+add,h,m);return [Job(id:1,role:'Garçom',company:'Hotel Vale Eventos',startsAt:d(1,18),endsAt:d(2,2),value:160,address:'Av. das Nações Unidas, 12551',city:'São Paulo',state:'SP',dressCode:'Calça preta, camisa branca e sapato social preto. O avental é fornecido pelo local.',notes:'Evento corporativo. Experiência anterior é um diferencial. Seja pontual e compareça com documento.',distanceKm:2.1),Job(id:2,role:'Recepcionista',company:'SP Eventos',startsAt:d(2,8),endsAt:d(2,16),value:180,address:'Av. Paulista, 900',city:'São Paulo',state:'SP',dressCode:'Social preto.',notes:'Recepção e orientação de convidados.',companyRating:4.8,candidates:5,distanceKm:3.4),Job(id:3,role:'Aux. Cozinha',company:'Bistrô Central',startsAt:d(3,14),endsAt:d(3,22),value:150,address:'Rua Central, 50',city:'São Paulo',state:'SP',dressCode:'Calçado fechado e calça preta.',notes:'Apoio de preparação e organização.',companyRating:4.7,candidates:2,distanceKm:1.8)];}
  static List<Assignment> demoAssignments(){final job=demoJobs().first;return [Assignment(id:901,shiftId:job.id,role:job.role,company:job.company,startsAt:job.startsAt,endsAt:job.endsAt,value:job.value,status:'confirmed',address:job.address,city:job.city,state:job.state)];}
}
