import 'package:flutter/material.dart';
import '../theme/app_theme.dart';

class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});
  @override
  Widget build(BuildContext context) {
    return ListView(padding:const EdgeInsets.fromLTRB(16,20,16,100),children:[
      const Text('Perfil',style:TextStyle(fontSize:27,fontWeight:FontWeight.w900)),const SizedBox(height:16),
      Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white,border:Border.all(color:TpColors.line),borderRadius:BorderRadius.circular(16)),child:const Column(children:[CircleAvatar(radius:44,backgroundColor:TpColors.blueSoft,child:Text('J',style:TextStyle(fontSize:30,color:TpColors.blue,fontWeight:FontWeight.w900))),SizedBox(height:10),Text('Juliana Alves',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text('Garçom • Recepcionista',style:TextStyle(color:TpColors.muted,fontSize:11)),SizedBox(height:12),_Verified(),SizedBox(height:18),Row(children:[Expanded(child:_Score(label:'Presença',value:'98%',icon:Icons.groups_rounded)),SizedBox(width:8),Expanded(child:_Score(label:'Pontualidade',value:'95%',icon:Icons.schedule_rounded))])])),
      const SizedBox(height:13),const _Menu(icon:Icons.badge_outlined,title:'Documentos verificados',subtitle:'4 documentos aprovados'),const _Menu(icon:Icons.star_outline_rounded,title:'Reputação',subtitle:'42 turnos concluídos'),const _Menu(icon:Icons.account_balance_wallet_outlined,title:'Dados de pagamento',subtitle:'Pix cadastrado'),const _Menu(icon:Icons.help_outline_rounded,title:'Ajuda e suporte',subtitle:'Fale com a TurnoPronto')
    ]);
  }
}
class _Verified extends StatelessWidget{const _Verified();@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:8),decoration:BoxDecoration(color:TpColors.greenSoft,borderRadius:BorderRadius.circular(20)),child:const Row(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.verified_user_rounded,color:TpColors.green,size:18),SizedBox(width:5),Text('Confiabilidade 97%',style:TextStyle(color:Color(0xFF0A8D50),fontWeight:FontWeight.w800,fontSize:11))]));}
class _Score extends StatelessWidget{const _Score({required this.label,required this.value,required this.icon});final String label,value;final IconData icon;@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(border:Border.all(color:TpColors.line),borderRadius:BorderRadius.circular(12)),child:Column(children:[Icon(icon,color:TpColors.blue),const SizedBox(height:4),Text(value,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),Text(label,style:const TextStyle(fontSize:9,color:TpColors.muted))]));}
class _Menu extends StatelessWidget{const _Menu({required this.icon,required this.title,required this.subtitle});final IconData icon;final String title,subtitle;@override Widget build(BuildContext context)=>Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,border:Border.all(color:TpColors.line),borderRadius:BorderRadius.circular(13)),child:Row(children:[Container(width:40,height:40,decoration:BoxDecoration(color:TpColors.blueSoft,borderRadius:BorderRadius.circular(10)),child:Icon(icon,color:TpColors.blue,size:20)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:12)),Text(subtitle,style:const TextStyle(color:TpColors.muted,fontSize:9))])),const Icon(Icons.chevron_right_rounded,color:TpColors.muted)]));}
